HS Rounding Senior:
  constraints:
  - type: min_by_period
    weeks: 2
    resident_years:
    - R2
  - type: max_by_period
    weeks: 4
    resident_years:
    - R2
  - type: min_contiguity_in_period
    weeks: 2
    resident_years:
    - R2
  - type          : exact_by_period
    weeks         : 8
    resident_years:
    - R3
  - type: min_contiguity_in_period
    weeks: 4
    resident_years:
    - R3
  fulfilled_by:
  - Orange HS Senior
  - Green HS Senior
HS Admitting Senior:
  constraints:
  - type: min_by_period
    weeks: 5
    resident_years:
    - R2
  - type: max_by_period
    weeks: 6
    resident_years:
    - R2
  - type : min_contiguity_in_period
    weeks: 2
    resident_years:
    - R2
  fulfilled_by:
  - Purple/Consults
ICU Senior:
  constraints:
  - type: min_by_period
    weeks: 4
    resident_years:
    - R2
  - type          : min_contiguity_in_period
    weeks         : 4
    resident_years:
    - R2
  fulfilled_by:
  - SHMC ICU Senior
Systems of Medicine:
  constraints:
  - type: min_by_period
    weeks: 2
    resident_years:
    - R2
  - type: min_contiguity_in_period
    weeks: 2
    resident_years:
    - R2
  fulfilled_by:
  - Systems of Medicine
Elective:
  constraints:
  - type: min_by_period
    weeks         : 10
    resident_years:
    - R2
  - type          : max_by_period
    weeks         : 30
    resident_years:
    - R2
  - type          : min_by_period
    weeks         : 10
    resident_years:
    - R3
  - type: max_by_period
    weeks: 30
    resident_years:
    - R3
  fulfilled_by:
  - Elective
Ethics:
  constraints:
  - type: exact_by_period
    weeks: 1
    resident_years:
    - R2
    - R3
  fulfilled_by:
  - Ethics
Ambulatory Senior:
  constraints:
  - type: min_by_period
    weeks: 4
    resident_years:
    - R2
  - type: min_contiguity_in_period
    weeks: 2
    resident_years:
    - R2
  - type: min_by_period
    weeks: 4
    resident_years:
    - R3
  - type: min_contiguity_in_period
    weeks: 2
    resident_years:
    - R3
  fulfilled_by:
  - STHC Senior
SHMC Night Senior:
  constraints:
  - type: exact_by_period
    weeks: 4
    resident_years:
    - R2
  - type: min_contiguity_in_period
    weeks: 4
    resident_years:
    - R2
  - type: min_by_period
    weeks: 1
    resident_years:
    - R3
  - type: max_by_period
    weeks: 2
    resident_years:
    - R3
  fulfilled_by:
  - SHMC Night Senior
Vacation:
  constraints:
  - type: exact_by_period
    weeks: 4
    resident_years:
    - R2
  - type: exact_by_period
    weeks: 3
    resident_years:
    - R3
  fulfilled_by:
  - Vacation
